### ISSUE TITLE
AWS ACCESS_KEY

### ISSUE THREAD

**Issue by Faiza-Haque** [swe-thinhnguyen1701/TeaLicious#12]
<Message>User: arn:aws:iam::471112628324:user/Faiza is not authorized to perform: s3:ListBucket on resource: "arn:aws:s3:::tea-images" because no identity-based policy allows the s3:ListBucket action</Message>

I got denied from looking at the image when I clicked on it.

**Comment by swe-thinhnguyen1701** [comment]
I already update your AWS access key, please re-run `npm run seed` at the root folder.

**Comment by Faiza-Haque** [comment]
Thank you!!
