### ISSUE TITLE
Alert is missing on product page

### ISSUE THREAD

**Issue by goodritu1** [swe-thinhnguyen1701/TeaLicious#61]
when we enter the correct number between 0 or less than stock we get alert "tea is added" but when we enter 0 or more than stock backend works fine as it doesn't add to the cart but it doesn't show any message for user.

![with prompt](https://github.com/user-attachments/assets/96f70ec6-ed50-4aeb-8c21-35d1a448508d)
![no prompt](https://github.com/user-attachments/assets/d2dc386a-f485-44ef-9f0a-997a01fbda59)

**Comment by Faiza-Haque** [comment]
Hi Ritu, this issue has be resolved by adding this code-alert("Invalid quantity. Must be greater than 0 or less than stock") on the ProductDetail.jsx page. Thank you!
