### ISSUE TITLE
inconsistent behaviour of cart page

### ISSUE THREAD

**Issue by goodritu1** [swe-thinhnguyen1701/TeaLicious#62]
cart is updating when we add but not updating when we remove items

![cart](https://github.com/user-attachments/assets/abb09f85-0558-4423-89f5-a12d8a04d533)

**Comment by Faiza-Haque** [comment]
Hi Ritu, I have resolved the isuue. Adding this code refetchQueries: [GET_ME]  for the remove item mutation has made the shopping cart update when you remove your item selected.
